spring:
  #h2 datasource for dev enviroment:
  datasource:
    url: jdbc:h2:file:./data/covid-analytics;MODE=MySQL
                                             #MODE=PostgreSQL | MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
  #h2 console for minor testing
  h2:
    console:
      path: '/dbconsole'
      enabled: true
