spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:${DB_PORT:5432}/${DB_NAME:covid-analytics}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver #com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false