spring:
  application:
    name: covid-analytics
  profiles:
    active: dev

#App info
app:
  name: @project.name@
  version: @project.version@
  secrets:
    key: ${JWT:JNN324KUJN23UN4UI231H798N798CN987N198N908N8DN8}

server:
  port: ${PORT:8080}